//----------CAÑAS
import CañaLexusChaiten from "../img/CañaLexusChaiten.jpg";
import CañaSpinitRainForestII from "../img/CañaSpinitRainForestII.jpg";
import CañaSaintCarbonTech from "../img/CañaSaintCarbonTech.png";
import CañaWaterdogBlackGFeeder from "../img/CañaWaterdogBlackGFeeder.jpg";
import CañaAlbatrosMarea from "../img/CañaAlbatrosMarea.jpg";
import CañaTechFoxrot from "../img/CañaTechFoxrot.jpg";
import CañaKunnanSilverside from "../img/CañaKunnanSilverside.jpg";
import CañaKunnanSilverside400 from "../img/CañaKunnanSilverside400.jpg";
import CañaShimanoFxC60mc26 from "../img/CañaShimanoFxC60mc26.jpg";
import CañaSpinitTornado from "../img/CañaSpinitTornado.png";
//----------REELS
import YukiStarSurf from "../img/YukiStarSurf.jpeg";
import OkumaCeymarCxt65 from "../img/OkumaCeymarCxt65.jpg";
import ReelRotativoHuevitoBanax from "../img/ReelRotativoHuevitoBanax.jpg";
import ReelFrontalShimanoSiennaFg4000 from "../img/ReelFrontalShimanoSiennaFg4000.jpg";
//----------ACCESORIOS PESCA
import BobinaNylonMasterguilZ4 from "../img/BobinaNylonMasterguilZ4.jpg";
import BobinaNylonMasterguilZ5TanzaMonofilamento from "../img/BobinaNylonMasterguilZ5TanzaMonofilamento.jpg";
import CajadePescaColganteFlounder from "../img/CajadePescaColganteFlounder.jpg";
//----------MOCHILAS
import MochilaBambooAdventure70Lts from "../img/MochilaBambooAdventure70Lts.jpg";
import MochilaSpinitTemuco24lts from "../img/MochilaSpinitTemuco24lts.jpg";
import MochilaWaterdogCracco70lts from "../img/MochilaWaterdogCracco70lts.jpg";
import MochilaDoiteCervino70Lts from "../img/MochilaDoiteCervino70Lts.jpg";
//----------CARPAS
import CarpaSpinitHolliday4P from "../img/CarpaSpinitHolliday4P.jpg";
import CarpaBambooExpedition6p from "../img/CarpaBambooExpedition6p.jpg";
//----------RECIPIENTES TÉRMICOS
import VasoTérmicoWaterdogOlivera450 from "../img/VasoTérmicoWaterdogOlivera450.jpg";
//----------LINTERNAS
import LinternaSpinitHL800R from "../img/LinternaSpinitHL800R.jpg";
//----------ACCESORIOS CAMPING
import MultifunciónTrentoClassic8 from "../img/MultifunciónTrentoClassic8.jpg";
//----------REPOSERAS Y SILLONES
import SillóndeAluminioAlumelArt130AltoReforzadoTiras from "../img/SillóndeAluminioAlumelArt130AltoReforzadoTiras.jpg";
//----------SOMBRILLAS
import SombrilladeAluminioAlumel2MtsReclinable from "../img/SombrilladeAluminioAlumel2MtsReclinable.jpeg";
//----------CONSERVADORAS
import ConservadoraHelatodo28lts from "../img/ConservadoraHelatodo28lts.jpg";
const products = [
  {
    id: 1,
    name: "Caña Lexus Chaiten",
    image: CañaLexusChaiten,
    price: 15000,
    category: "Canas",
    section: "Pesca",
    description: [
      "Material: Grafito de alto módulo.",
      "Tramos : 2.",
      "Mango : corcho.",
      "Pasahilos livianos de 1 pata.",
      "Caña ideal para la pesca de pejerrey y lenguado. También pesca de truchas.",
    ],
    stock: 10,
  },
  {
    id: 2,
    name: "Caña Spinit Rain Forest II",
    image: CañaSpinitRainForestII,
    price: 9960,
    category: "Canas",
    section: "Pesca",
    description: [
      "Material: Grafito.",
      "Porta reel con rosca inferior con inserto de corcho.",
      "Mango descubierto con pomo de corcho.",
      "6 Pasa Hilos + Puntero.",
      "Largo: 1.98 mts.",
      "Poder: 8-17 Lb.",
      "Acción: Rápida.",
      "2 Tramos.",
    ],
    stock: 5,
  },
  {
    id: 3,
    name: "Caña Saint Carbon Tech",
    image: CañaSaintCarbonTech,
    price: 15000,
    category: "Canas",
    section: "Pesca",
    description: [
      "9 pasahilos + puntera.",
      "Tipo de pasahilos: óxido de aluminio.",
      "Material de mango: E.V.A.",
      "Blank: Carbono Especial IM6.",
      "Peso aproximado: 223g",
    ],
    stock: 6,
  },
  {
    id: 4,
    name: "Caña Waterdog Black G Feeder",
    image: CañaWaterdogBlackGFeeder,
    price: 19500,
    category: "Canas",
    section: "Pesca",
    description: [
      "Composición: POWERFLEX.",
      "Pasahilos: TITANIUM.",
      "Tres tips: 3 - 4 - 5 oz.",
      "Porta Reel: Rosca.",
      "Empuñadura: Corcho y Eva.",
    ],
    stock: 3,
  },
  {
    id: 5,
    name: "Caña Albatros Marea",
    image: CañaAlbatrosMarea,
    price: 12000,
    category: "Canas",
    section: "Pesca",
    description: [
      "Marca : Albatros.",
      "Composición grafito.",
      "Acción HH 180grs.",
      "Mango de eva y portareel a rosca.",
      "3 tramos.",
      "6 pasahilos",
      "Tipo de caña: lanzar",
    ],
    stock: 8,
  },
  {
    id: 6,
    name: "Caña Tech Foxrot",
    image: CañaTechFoxrot,
    price: 25000,
    category: "Canas",
    section: "Pesca",
    description: [
      "Largo: 14′. (4.20mts).",
      "Tramos: 3.",
      "Pasahílos de SIC: 8.",
      "Potencia: extra heavy. 10-30 lbs.",
      "Grafito de alto módulo.",
      "Mango desnudo con goma antideslizante.",
      "Refuerzo con anillo metálico en enchufe directo macho-hembra.",
      "Surfcasting para reel rotativo.",
    ],
    stock: 7,
  },
  {
    id: 7,
    name: "Caña Kunnan Silverside 4.50",
    image: CañaKunnanSilverside,
    price: 9570,
    category: "Canas",
    section: "Pesca",
    description: [
      "Composición: IM6 GRAPHITE.",
      "Para plomada: 15 a 40 g",
      "Pasahilos: ZIRCONIUM OXIDE LIGHT.",
      "Porta Reel: CREMALLERA CON TOPES DE GOMA",
    ],
    stock: 8,
  },
  {
    id: 8,
    name: "Caña Kunnan Silverside 4.00",
    image: CañaKunnanSilverside400,
    price: 9240,
    category: "Canas",
    section: "Pesca",
    description: [
      "Composición: IM6 GRAPHITE.",
      "Para plomada: 15 a 40 g",
      "Pasahilos: ZIRCONIUM OXIDE LIGHT.",
      "Porta Reel: CREMALLERA CON TOPES DE GOMA",
    ],
    stock: 8,
  },
  {
    id: 9,
    name: "Caña Shimano Fx C60mc2 6 - 15 Lbs Pesca Baitcast Con Gatillo",
    image: CañaShimanoFxC60mc26,
    price: 5800,
    category: "Canas",
    section: "Pesca",
    description: [
      "Siempre que busques equipos económicos, es imposible que no prestes atención a la línea FX de Shimano! Porque no solo es una línea con precios accesibles, sino que esta cuidadosamente diseñada para la batalla, para las grandes jornadas de pesca, para cuando necesitas que tu equipo te sea leal!",
      "Caña de fibra de vidrio.",
      "Mango gatillo de eva.",
      "6 + 1 Pasahilos aptos para mono y multifilamento.",
      "Puntero de óxido de aluminio.",
      "Para reel Rotativo.",
      "6 - 15 lbs de resistencia.",
      "Peso de señuelos recomendados de 1/4 - 3/4oz.",
      "No incluye funda",
    ],
    stock: 12,
  },
  {
    id: 10,
    name: "Caña Spinit Tornado",
    image: CañaSpinitTornado,
    price: 12050,
    category: "Canas",
    section: "Pesca",
    description: [
      "No incluye funda.",
      "Tramos: 3.",
      "Acción: Extra Heavy - Extra Fast.",
      "Soporte reel: Spinning.",
      "Peso señuelo: 100 a 250g.",
      "Material: Fiberglass.",
      "Tipo de pesca: Surfcasting",
    ],
    stock: 6,
  },
  {
    id: 11,
    name: "Yuki Star Surf",
    image: YukiStarSurf,
    price: 47000,
    category: "Reels",
    section: "Pesca",
    description: [
      "7 rulemanes.",
      "Relación de giro  4.6 :1.",
      "3 carreteles de surfcasting.",
      "Peso : 635 Grs.",
      "Potencia de freno : 15 Kgrs.",
    ],
    stock: 6,
  },
  {
    id: 12,
    name: "Okuma Ceymar Cxt 65",
    image: OkumaCeymarCxt65,
    price: 31000,
    category: "Reels",
    section: "Pesca",
    description: [
      "8 Rulemanes.",
      "Relación de transmisión 4.8:1.",
      "Capacidad 0.35 mm/340 mts., 0.40 mm/ 260 mts, 0.50 mm / 160 mts",
      "Peso : 650 grs.",
      "Material del cuerpo : Grafito",
      "Tipo de Freno : Delantero",
      "El nuevo reel de spinning Ceymar tiene una impresionante ingeniería. Un sistema de engranaje elíptico de precisión. Mecanizado de aluminio , bobina anodizado 2 tonos.",
      "RESII : Equipo equilibrado sistema de ecualización de Rotor.",
      "La calidad de Okuma reflejada en este reel.",
    ],
    stock: 8,
  },
  {
    id: 13,
    name: "Reel Rotativo Huevito Banax",
    image: ReelRotativoHuevitoBanax,
    price: 54890,
    category: "Reels",
    section: "Pesca",
    description: [
      "Cuerpo de grafito.",
      "disponible en derecho y izquierdo.",
      "Carretel grande en aluminio Anodizado.",
      "5 rulemanes blindados (made in KOREA).",
      "Radio de giro: 7.1:1.",
      "Capacidad: 0.37mm - 210mts.",
      "Manija extra grande en aluminio anodizado alivianada.",
      "Manija adicional.",
      "Capacidad de arrastre hasta 14kg",
      "Peso 308gr.",
      "Embrague multidisco",
      "Devanador instantáneo",
      "Freno centrífugo.",
    ],
    stock: 6,
  },
  {
    id: 14,
    name: "Reel Frontal Shimano Sienna Fg 4000",
    image: ReelFrontalShimanoSiennaFg4000,
    price: 15630,
    category: "Reels",
    section: "Pesca",
    description: [
      "Shimano, marca japonesa presente en el mercado de la pesca desde 1970, se destaca por la ingeniería de precisión presente tanto en sus productos, como en los procesos de fabricación.",
      "El reel frontal es el más usado en el mundo. Tiene un devanado automático excelente, que acomoda el nailon de manera prolija, y permite buenos lances.",
      "Manija intercambiable: Este tipo de manija suma practicidad y comodidad durante la pesca, ya que se puede colocar tanto del lado derecho, como del izquierdo.",
    ],
    stock: 8,
  },
  {
    id: 17,
    name: "Bobina Nylon Masterguil Z4",
    image: BobinaNylonMasterguilZ4,
    price: 2050,
    category: "Accesorios",
    section: "Pesca",
    description: [
      "Bobina de 1/4 lbs. (113 grs).",
      "Color: Amarillo Fluor",
      "Medidas: 0.28 mm / 4.93 kg / 1570 mts ; 0.31 mm / 5.96 kg / 1320 mts; 0.33 mm / 6.17 kg / 1175 mts;0.35 mm / 7.40 kg / 1050 mts;0.37 mm / 8.16 kg / 930 mts;0.40 mm / 9.73 kg / ;0.50 mm / 14.70 kg /",
    ],
    stock: 13,
  },
  {
    id: 18,
    name: "Bobina Nylon Masterguil Z5 Tanza Monofilamento",
    image: BobinaNylonMasterguilZ5TanzaMonofilamento,
    price: 2700,
    category: "Accesorios",
    section: "Pesca",
    description: [
      "Nylon Masterguil Z 5 ideal para lograr distancia por su resistencia y baja memoria. ",
    ],
    stock: 10,
  },
  {
    id: 19,
    name: "Caja de Pesca Colgante Flounder",
    image: CajadePescaColganteFlounder,
    price: 9550,
    category: "Accesorios",
    section: "Pesca",
    description: [
      "Ancho 28 cm.",
      "Alto 35 cm.",
      "Profundidad 23 cm.",
      "Compartimiento con separadores para accesorios",
      "Compartimiento grande tipo balde.",
      "Material PVC de alta resistencia.",
      "Correa de transporte.",
    ],
    stock: 12,
  },
  {
    id: 22,
    name: "Mochila Bamboo Adventure 70 Lts",
    image: MochilaBambooAdventure70Lts,
    price: 49900,
    category: "Mochila",
    section: "Camping",
    description: [
      "Tela Nylon Ripstop 600D recubrimiento PU.",
      "Bolsillo frontal y laterales extensibles, laterales porta botellas.",
      "Correa porta piqueta, accesorios y de comprensión lateral.",
      "Arnés que organiza el peso.",
      "Hombreras acolchadas.",
      "Correas anatómicas regulables.",
      "Ajuste de pecho y cintura.",
      "Broche con guía.",
      "Espaldar V1-SYSTEM, regulable con velcro recubiertos.",
      "Barras de aluminio precurvado y acolchados.",
      "Compartimiento para hidratación y funda cubre mochila.",
      "Cubre mochila incorporada.",
    ],
    stock: 8,
  },
  {
    id: 23,
    name: "Mochila Spinit Temuco 24lts",
    image: MochilaSpinitTemuco24lts,
    price: 15050,
    category: "Mochila",
    section: "Camping",
    description: [
      "Peso aproximado: 0,76kg.",
      "Material: Poliéster DOBBY 200D PU, resistente al agua.",
      "Medidas: 45 x 32 x 19cm.",
      "Dos compartimientos principales.",
      "Bolsillo delantero.",
      "Bolsillos laterales elastizados.",
      "Correas laterales de compresión.",
      "Cubremochilas en el bolsillo inferior; Color fluor variable.",
    ],
    stock: 5,
  },
  {
    id: 24,
    name: "Mochila Waterdog Cracco 70 lts",
    image: MochilaWaterdogCracco70lts,
    price: 44000,
    category: "Mochila",
    section: "Camping",
    description: [
      "Peso aproximado: 1,17 kg.",
      "Material: POLYESTER DIAMOND RIPSTOP 200D + POLYESTER 600D.",
      "Medidas: 35 x 27 x 75 cm.",
      "Gran compartimento con acceso superior..",
      "2 Compartimiento especial para bolsa y apertura para H O.",
      "Dos bolsillos laterales.",
      "Espaldar fijo de EVA extra confort recubierto con mesh.",
      "Amplio cinturón con acolchado lumbar, con bolsillo.",
      "Hombreras acolchadas con mesh.",
      "Cintas compresoras laterales.",
      "Cintas de pecho regulables.",
      "Salida para sistema de audio.",
      "Manija de agarre.",
      "Cubre mochila.",
    ],
    stock: 7,
  },
  {
    id: 25,
    name: "Mochila Doite Cervino 70 Lts",
    image: MochilaDoiteCervino70Lts,
    price: 97690,
    category: "Mochila",
    section: "Camping",
    description: [
      "Peso aproximado: 2,7 kg.",
      "Material: POLYESTER INTERIOR, NYLON EXTERIOR.",
      "Medidas: 18 x 30 x 70 cm.",
      "Gran compartimento con acceso superior..",
      "2 Compartimiento especial para bolsa y apertura para H O.",
    ],
    stock: 9,
  },
  {
    id: 26,
    name: "Carpa Spinit Holliday 4 P.",
    image: CarpaSpinitHolliday4P,
    price: 94130,
    category: "Carpa",
    section: "Camping",
    description: [
      "Capacidad: 4 personas.",
      "Dos habitaciones y comedor con piso.",
      "Cubretecho poliester P.U. 190 T.",
      "Costuras termoselladas.",
      "Columna de agua 1500 mm. EF: Imp. 2000 mm.",
      "Interior poliester impermeable y respirable.",
      "Mosquitero NO SEE UM.",
      "Piso polietileno 10 x 12 g/m2.",
      "2 entradas + 2 habitaciones + 1 comedor con piso.",
      "Varillas fibra de vidrio.",
      "Peso aprox 8 kg.",
      "Cada habitacion mide 1,40 mts. ancho x 2,20 mts. largo x 1,50 mts. de alto.",
      "El comedor central mide 1,80 mts. ancho x 2,20 mts. largo x 1,90 mts. de alto.",
      "Incluye bolso de transporte.",
    ],
    stock: 5,
  },
  {
    id: 27,
    name: "Carpa Bamboo Expedition 6p",
    image: CarpaBambooExpedition6p,
    price: 57000,
    category: "Carpa",
    section: "Camping",
    description: [
      "2 ventanas en el Abside delantero.",
      "Costuras termoselladas",
      "Impermiabilidad 2000 mm.",
      "Piso de polietileno de 200 grs/m2.",
      "Varillas de fibra de vidrio.",
      "Respirador trasero.",
      "Altura: 1.90 mts.",
      "Largo: 4.40 mts.",
      "Ancho: 3.20 mts.",
      "Peso: 9.30 kg.",
      "Apertura lateral en el comedor.",
      "Acceso trasero con mosquitero y cierres dobles.",
    ],
    stock: 5,
  },
  {
    id: 30,
    name: "Vaso Térmico Waterdog Olivera 450",
    image: VasoTérmicoWaterdogOlivera450,
    price: 7900,
    category: "Recipiente_térmico",
    section: "Camping",
    description: [
      "CAPACIDAD: 450 ml.",
      "VASO 100% ACERO INOXIDABLE AISI 304.",
      "Doble pared de aislamiento.",
      "Medida: Alto: 18,5 cm / Diámetro Boca: 8 cm / Base: 7 cm.",
      "Peso: 280 g.",
      "Recubrimiento powder coated (WH, BK, CO).",
      "Tapa PLÁSTICA.",
      "Fácil de llenar.",
      "Apto bebidas frías y calientes.",
    ],
    stock: 12,
  },
  {
    id: 35,
    name: "Linterna Spinit HL800R Frontal/Mano",
    image: LinternaSpinitHL800R,
    price: 7220,
    category: "Linterna",
    section: "Camping",
    description: [
      "Multipropósito: Linterna de cabeza, de mano o de sujeción magnética.",
      "Batería recargable USB: 1x 18650.",
      "Potencia Máxima Lumen: 800.",
      "LED CREE 10W.",
      "Waterproof: IPX4.",
      "Modos: Alta - Media - Baja - Flash - SOS.",
      "Medidas: 23x110mm.",
      "Peso: 65g.",
      "Rango Máximo: 300mts.",
      "Uso: Táctico - Trabajo - Camping - Deportes.",
    ],
    stock: 12,
  },
  {
    id: 40,
    name: "Multifunción Trento Classic 8",
    image: MultifunciónTrentoClassic8,
    price: 2540,
    category: "Accesorios_camping",
    section: "Camping",
    description: [
      "Acero inoxidable 420C.",
      "Presentación en caja.",
      "8 Funciones:",
      "Hoja de corte en 6,5 cm.",
      "Abrelatas.",
      "Abrebotellas.",
      "Desaislador alambres.",
      "Sacacorchos.",
      "Punzón.",
      "Enebrador.",
      "Anillas",
    ],
    stock: 12,
  },
  {
    id: 45,
    name: "Sillón de Aluminio Alumel Art 130 Alto Reforzado Tiras",
    image: SillóndeAluminioAlumelArt130AltoReforzadoTiras,
    price: 17100,
    category: "Reposera_Sillon",
    section: "Playa",
    description: [
      "Material: Aluminio.",
      "Resiste hasta 160 KG.",
      "Tipo de tela: Cinta cruzadas.",
      "Apoyabrazos anodizado brillante (brillo eterno).",
      "1 Posición.",
      "Medidas:",
      "Plegada: 63 X 61 X 79cm.",
      "Respaldo: 52 x 48cm.",
      "Asiento: 52 x 42.5cm.",
      "Altura: 41cm.",
      "Altura total: 69cm",
    ],
    stock: 12,
  },
  {
    id: 50,
    name: "Sombrilla de Aluminio Alumel 2 Mts Reclinable",
    image: SombrilladeAluminioAlumel2MtsReclinable,
    price: 39300,
    category: "Sombrilla",
    section: "Playa",
    description: [
      "Modelo: Sombrilla Aluminio 2.00 Mts Lona Acrílica.",
      "Diámetro total: 200 CM = 2.00 Mts.",
      "Altura total: 250 CM.",
      "Estructura: aluminio reforzado y anodizado.",
      "Sin partes plásticas, todo aluminio.",
      "Grosor varillas: 1 CM.",
      "Espesor caño: 2.5 MM.",
      "Tela: lona acrílica.",
      "Bonete: madera torneada.",
      "Bolso para transporte.",
      "Lanza de aluminio.",
    ],
    stock: 12,
  },
  {
    id: 55,
    name: "Conservadora Helatodo 28 lts.",
    image: ConservadoraHelatodo28lts,
    price: 39300,
    category: "Conservadora",
    section: "Playa",
    description: [
      "Capacidad 28 Litros.",
      "Tapa hermética Krack Sistem.",
      "Tapón de desagote y bandeja posavasos.",
      "Entran 6 botellas de 2.25 lts.",
      "Empuñadura anatómica de cierre hermético para evitar fugas de temperatura.",
      "Única con tapón de desagote exterior.",
      "Excelente diseño, calidad y tecnología de aislación, conservan el frío durante todo el día.",
    ],
    stock: 12,
  },
];
export default products;
